# Dataset and dataloader parameters
dataset: 'nuScenes'
version: 'v1.0-trainval'
agent_setting: 'single_agent'
input_representation: 'graphs'

train_set_args: &ds_args
  split: 'train'
  t_h: 2
  t_f: 6
  map_extent: [ -50, 50, -20, 80 ]
  polyline_resolution: 1
  polyline_length: 20
  traversal_horizon: 15
  random_flips: True

val_set_args:
  <<: *ds_args
  split: 'val'
  random_flips: False

test_set_args:
  <<: *ds_args
  split: 'val'
  random_flips: False

batch_size: 32
num_workers: 4


# Encoder parameters
encoder_type: 'motif_encoder_v6'
encoder_args:
  motif_feat_size: 2600
  motif_enc_size: 32
  # motif_influence_radius: 20
  motif_influence_radius: 15
  # motif_influence_radius: 10
  # motif_influence_radius: 5
  motif_default_size: 10
  motif_type: 'motif4'
  yaw_thresh: '3*np.pi/4'
  #  motif_type: 'motif Laplacian'
  #motif_type: 'normalized motif Laplacian'
#  latent_temperature: 5.0
  fuse_temperature: 2.0
  target_agent_feat_size: 5
  target_agent_emb_size: 32
  target_agent_enc_size: 32
  node_feat_size: 6
  node_emb_size: 32
  node_enc_size: 32
  nbr_feat_size: 5
  nbr_emb_size: 32
  nbr_enc_size: 32
  num_gat_layers: 2

# Aggregator parameters
aggregator_type: 'motif_agg_v5'
aggregator_args:
  pre_train: False
  target_agent_enc_size: 64
  node_enc_size: 32
  pi_h1_size: 32
  pi_h2_size: 32
  horizon: 15
  num_samples: 1000
  emb_size: 128
  num_heads: 32


# Decoder parameters
decoder_type: 'motif_decoder_v5'
decoder_args:
  num_samples: 1000
  op_len: 12
  hidden_size: 128
  encoding_size: 192
  agg_type: 'sample_specific'
  lv_dim: 5
  num_clusters: 10


# Optimizer parameters
optim_args:
  lr: 0.001
  scheduler_step: 10
  scheduler_gamma: 0.5


losses: ['min_ade_k', 'pi_bc']
loss_weights: [1, 0.5]
loss_args:
  - k: 10
  - dummy: 0


tr_metrics: ['min_ade_k', 'miss_rate_k', 'pi_bc']
tr_metric_args:
  - k: 10
  - k: 10
    dist_thresh: 2
  - dummy: 0

val_metrics: ['min_ade_k', 'min_ade_k', 'min_ade_k', 'min_fde_k', 'min_fde_k', 'min_fde_k', 'miss_rate_k', 'miss_rate_k', 'miss_rate_k', 'pi_bc']
val_metric_args:
  - k: 1
  - k: 5
  - k: 10
  - k: 1
  - k: 5
  - k: 10
  - k: 1
    dist_thresh: 2
  - k: 5
    dist_thresh: 2
  - k: 10
    dist_thresh: 2
  - dummy: 0



log_freq: 100
